-- CTSA CLIC Metric 
-- CDM: i2b2/ACT 
-- RDB Dialect: SQLServer
-- Creation Date: 4/5/2021
-- Ontology Version: 4.0

-- Caveats:  ACT does not support the following by default, placeholders have been provided
--           if you support the domain locally
--           NLP, Notes, SNOMED Procedures or Diagnosis
-- AdapterMapping: For sites that utilize a custom ACT AdapterMapping file replace the paths included in this
--                 script with the path(s) mapped to the ACT path provided.
--
--		   Example change below
--
--                 WITH MAPPED_DOMAIN AS (      
--    		   	SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION
--			       WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD9\%'
--        		UNION
--    			SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION
--      	     		       WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD10\%'
--                 )
--
--		   CHANGE TO (RIGHT COLUMN PATH)
--
--                 WITH MAPPED_DOMAIN AS (      
--    		   	SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION
--			       WHERE CONCEPT_PATH LIKE '\LOCAL\PATH\MAPPED TO\ACT\Procedures\ICD9\%'
--        		UNION
--    			SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION
--      	     	       WHERE CONCEPT_PATH LIKE '\LOCAL\PATH\MAPPED TO\ACT\Procedures\ICD10\%'
--                 )
-- Multifact table
-- Indexes
-- 

SELECT CURRENT_TIMESTAMP;

--select * from #CTSA_CLIC_METRIC;
-- Create dest table
--IF OBJECT_ID('#CTSA_CLIC_METRIC', 'U') IS NOT NULL          -- Drop table if it exists
--  DROP TABLE #CTSA_CLIC_METRIC;
IF OBJECT_ID(N'tempdb..#CTSA_CLIC_METRIC') IS NOT NULL DROP TABLE #CTSA_CLIC_METRIC

CREATE TABLE #CTSA_CLIC_METRIC (
	variable_name			VARCHAR(100)  NOT NULL,
        one_year            INT   NULL,
	five_year		    INT   NULL
);


--  Variable: data_model
--  Acceptable values:  1=PCORNet, 2=OMOP, 3=TriNetX, 4=i2b2/ACT

INSERT INTO #CTSA_CLIC_METRIC
SELECT 
	'data_model' as variable_name
	,'4' as one_year -- 4 = i2b2/ACT
	,'4' as five_year -- 4 = i2b2/ACT
;

--Edit this for your site 
--change the edit_this_for_your_site to '0', '1' or null
-- this will error out if not modified
--Answers '0' your site does not have NLP /Notes capability, '1' your site does have NLP / Notes does  have NLP /Notes capability NULL if the model does not support  NLP
INSERT INTO #CTSA_CLIC_METRIC
SELECT
	'nlp_any' as variable_name
	, edit_this_for_your_site as one_year
	, edit_this_for_your_site as five_year
;
   
-- Unique ENCOUNTERS 
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'total_encounters' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM OBSERVATION_FACT OBS WHERE OBS.START_DATE BETWEEN CAST('2020/01/01' AS DATE) AND CAST('2020/12/31' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM OBSERVATION_FACT OBS WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;



-- Unique PATIENTS 
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'total_patients' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- Unique PATIENTS with gender
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'uniq_pt_with_gender' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND (PAT.SEX_CD IS NULL OR PAT.SEX_CD <> 'DEM|SEX:NI')
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND (PAT.SEX_CD IS NULL OR PAT.SEX_CD <> 'DEM|SEX:NI')
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- Unique PATIENTS WITH BIRTH DATES
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'uniq_pt_with_age' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND PAT.BIRTH_DATE IS NOT NULL
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND PAT.BIRTH_DATE IS NOT NULL
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- UNIQUE PATIENTS OVER 12
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'total_pt_gt_12' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
            AND PAT.BIRTH_DATE IS NOT NULL AND DATEDIFF(YEAR, PAT.BIRTH_DATE, OBS.START_DATE) > 12 
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
            AND PAT.BIRTH_DATE IS NOT NULL AND DATEDIFF(YEAR, PAT.BIRTH_DATE, OBS.START_DATE) > 12 
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- UNIQUE PATIENTS WITH IMPLAUSIBLE AGES (TOO YOUNG)
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'uniq_pt_birthdate_in_future' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND PAT.BIRTH_DATE > '2021/12/31'
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM AND PAT.BIRTH_DATE > '2021/12/31'
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- UNIQUE PATIENTS WITH IMPLAUSIBLE AGES (TOO OLD)
INSERT INTO #CTSA_CLIC_METRIC
SELECT
  'uniq_pt_age_over_120' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
        AND ((PAT.DEATH_DATE IS NULL AND DATEDIFF(YEAR, PAT.BIRTH_DATE, '12-31-2020')  > 120)
            OR (DATEDIFF(YEAR, PAT.BIRTH_DATE, PAT.DEATH_DATE)  > 120))
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
       FROM OBSERVATION_FACT OBS
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
        AND ((PAT.DEATH_DATE IS NULL AND DATEDIFF(YEAR, PAT.BIRTH_DATE, '12-31-2020')  > 120)
            OR (DATEDIFF(YEAR, PAT.BIRTH_DATE, PAT.DEATH_DATE)  > 120))
        WHERE OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
;


-- Unique patients with procedures mapped to SNOMED -- THIS IS NOT SUPPORTED BY ACT - IF YOU HAVE THEM MODIFY PATH ACCORDINGLY 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SNOMED\%'
), 
METRIC AS (
SELECT
  'uniq_pt_snomed_proc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC
;

SELECT * FROM #CTSA_CLIC_METRIC;

-- Unique encounters with procedures mapped to SNOMED -- THIS IS NOT SUPPORTED BY ACT - IF YOU HAVE THEM MODIFY PATH ACCORDINGLY 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SNOMED\%'
), 
METRIC AS (
SELECT
  'uniq_enc_snomed_proc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with DIAGNOSIS mapped to SNOMED -- THIS IS NOT SUPPORTED BY ACT - IF YOU HAVE THEM MODIFY PATH ACCORDINGLY 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SNOMED\%'
), 
METRIC AS (
SELECT
  'uniq_pt_snomed_dx' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with DIAGNOSIS mapped to SNOMED -- THIS IS NOT SUPPORTED BY ACT - IF YOU HAVE THEM MODIFY PATH ACCORDINGLY 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SNOMED\%'
), 
METRIC AS (
SELECT
  'uniq_enc_snomed_dx' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with a Note -- Not supported by ACT - Change path if your site supports it 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Notes\%'
), 
METRIC AS (
SELECT
  'uniq_pt_note' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with a Note -- Not supported by ACT - Change path if your site supports it 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Notes\%'
), 
METRIC AS (
SELECT
  'uniq_enc_note' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;



-- Unique patients with INSURANCE mapped to STANDARDIZED VALUES
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SDOH\76437-3\%'
), 
METRIC AS (
SELECT
  'uniq_pt_insurance_value_set' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with INSURANCE - UNMAPPED INSURANCE IS NOT COUNTABLE AT THIS TIME
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SDOH\76437-3\%'
), 
METRIC AS (
SELECT
  'uniq_pt_any_insurance_value' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with procedures mapped to ICD 10/9 -- 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD9\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD10\%'
), 
METRIC AS (
SELECT
  'uniq_pt_icd_proc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with procedures mapped to ICD 10/9 -- 
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD9\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\ICD10\%'
), 
METRIC AS (
SELECT
  'uniq_enc_icd_proc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with labs mapped to LOINC 
WITH MAPPED_LABS AS (
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Labs\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Lab\%'
), 
METRIC AS (
SELECT
  'uniq_pt_loinc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_LABS MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_LABS MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique ENCOUNTERS with labs mapped to LOINC 
WITH MAPPED_LABS AS (
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Labs\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Lab\%'
), 
METRIC AS (
SELECT
  'uniq_enc_loinc' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_LABS MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_LABS MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;



-- Unique patients with medications mapped to RXNORM or NDC 
WITH MAPPED_DOMAIN AS (
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\%'
), 
METRIC AS (
SELECT
  'uniq_pt_med_rxnorm' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with medications mapped to RXNORM or NDC
WITH MAPPED_DOMAIN AS (
    SELECT DISTINCT CONCEPT_CD as CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\%'
), 
METRIC AS (
SELECT
  'uniq_enc_med_rxnorm' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with diagnosis and conditions mapped to ICD9/10
WITH MAPPED_DOMAIN AS (
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Diagnosis\%'
), 
METRIC AS (
SELECT
  'uniq_pt_icd_dx' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with diagnosis and conditions mapped to ICD9/10
WITH MAPPED_DOMAIN AS (
    SELECT DISTINCT CONCEPT_CD as CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Diagnosis\%'
), 
METRIC AS (
SELECT
    'uniq_enc_icd_dx' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;



-- Unique patients with procedures mapped to HCPCS and CPT4
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\HCPCS\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\CPT4\%'
), 
METRIC AS (
SELECT
  'uniq_pt_cpt' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique encounters with procedures mapped to CPT and HCPCS
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\CPT4\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Procedures\HCPCS\%'
), 
METRIC AS (
SELECT
  'uniq_enc_cpt' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;



-- Unique patients with VITAL SIGN data mapped
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Vital Signs\%'
), 
METRIC AS (
SELECT
  'uniq_enc_vital_sign' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with smoking data mapped
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\SDOH\LP156992-2\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Diagnosis\ICD10\V2_2018AA\A20098492\A20160670\A18921523\A17812661\%'
), 
METRIC AS (
SELECT
  'uniq_pt_smoking' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
            AND PAT.BIRTH_DATE IS NOT NULL AND DATEDIFF(year, PAT.BIRTH_DATE, OBS.START_DATE) > 12 
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.ENCOUNTER_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
        JOIN PATIENT_DIMENSION PAT ON PAT.PATIENT_NUM = OBS.PATIENT_NUM 
            AND PAT.BIRTH_DATE IS NOT NULL AND DATEDIFF(YEAR, PAT.BIRTH_DATE, OBS.START_DATE) > 12 
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;


-- Unique patients with opioid abuse disorder
WITH MAPPED_DOMAIN AS (      
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\BPreparations\1819\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\BPreparations\352364\%' 
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\MPreparations\6813\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\NPreparations\1007909\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\NPreparations\7242\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\BPreparations\352364\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\NPreparations\214721\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Medications\MedicationsByAlpha\V2_12112018\RxNormUMLSRxNav\NPreparations\1545902\%'
        UNION
    SELECT CONCEPT_CD FROM  CONCEPT_DIMENSION WHERE CONCEPT_PATH LIKE '\ACT\Diagnosis\ICD10\V2_2018AA\A20098492\A20160670\A18921523\A17774215\%' -- OPIOID DISORDER
), 
METRIC AS (
SELECT
  'uniq_pt_opioid' AS VARIABLE_NAME,
  
   ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2020' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS ONE_YEAR,
    
    ( SELECT COUNT(DISTINCT OBS.PATIENT_NUM) CNT
        FROM MAPPED_DOMAIN MAP
        JOIN OBSERVATION_FACT OBS ON OBS.CONCEPT_CD = MAP.CONCEPT_CD AND OBS.START_DATE BETWEEN CAST('01-01-2016' AS DATE) AND CAST('12-31-2020' AS DATE)
    ) AS FIVE_YEAR
)
INSERT INTO #CTSA_CLIC_METRIC
SELECT VARIABLE_NAME, ONE_YEAR, FIVE_YEAR
FROM METRIC;

SELECT * FROM #CTSA_CLIC_METRIC;

select CURRENT_TIMESTAMP;
